spring:
  datasource:
    url: ${DB_JDBC}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none